services:
  mqtt:
    container_name: mqtt_server
    image: eclipse-mosquitto:2.0
    volumes:
      - "./mosquitto-data/config:/mosquitto/config"
      - "./mosquitto-data/data:/mosquitto/data"
      - "./mosquitto-data/log:/mosquitto/log"
    networks:
        shadownet:
            ipv4_address: $MQTTIP
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    environment:
#      - TZ=American/Detroit
      - ZIGBEE2MQTT_CONFIG_MQTT_USER=stl_admin
      - ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD=st2012
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=$MQTTIP
      - ZIGBEE2MQTT_CONFIG_FRONTEND_PORT=8080
    networks:
        shadownet:
            ipv4_address: $ZB2MQTTIP
    depends_on:
      - mqtt
networks:
    shadownet:
        name: shadownet
        external: true


### notes
### added zigbee2mqtt and mqtt server to external shadownet network using ipvlan l2 driver
# ports are not needed for l2 driver networks