services:
  shadownet_avp:
    container_name: shadownet_avp
    image: shadowtechlabs/dod:$BUILD
    volumes:
      - "./shadownet-config:/hunter/Software/Config"
      - "./shadownet-logs:/hunter/Software/logs"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    networks:
      shadownet:
        ipv4_address: $AVPIP
networks:
    shadownet:
        name: shadownet
        external: true
